# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a878f35262ec3285e327cad4ef11da4173af6e7afbfc729d8dbb744b00cd11aea590676b5df86143a661b2166a1bee3d98b773065ff544e199e09590dc4ba3

test:
  secret_key_base: 3c6442d287f31cf074ccd190a89b2e73dc7823c532f5fabe9de1eea047c612452893cbe5db967c11207c463a5136f089436d187237602a62bbb335847231d8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
